<?php

define("TITLE_INDEX", "TrophyLeagues - Manager online de fútbol");
define("DESCRIPTION_INDEX", "Dirigeix un equip, entrena els jugadors, gestiona la economía, juga partits i molt més a TrophyLeagues.");
define("KEYWORDS_INDEX", "TrophyLeagues, trophy, manager futbol, TL manager, joc futbol");
define("MENU_ABOUT", "¿Què és TL?");
define("MENU_NEWS", "Newsletter");
define("MENU_COOP", "Col·laborar");
define("MENU_FORUM", "Fòrums");
define("TITLE_REGISTER", "Apunta't a la versió Beta");
define("NAME", "Nom");
define("EMAIL", "Direcció de correu electrònic");
define("COUNTRY", "País");
define("SEND", "Enviar");
define("TITLE_ABOUT", "¿Que és <br />Trophy Leagues?");
define("ABOUT_DESCRIPTION", "El joc combina les funcions de direcció tècnica de l'equip, entrenaments, gestió econòmica del club, estadi, estètica, lligues i una comunitat d'apassionats pel fútbol. <br/> Trophy Leagues és un joc massiu i gratuït per navegador en què els jugadors administren el seu propi club de fútbol.");
define("ABOUT_ACTION", "No pots esperar ni un segon més per jugar-hi? Apunta't a la <a href='#form' class='tl-red'>versió beta</a>.");
define("TITLE_NEWS", "Novetats del joc");
define("NEWS_DESCRIPTION", "T'informarem de totes les novetats del joc, avenços, versions de prova i llançament.");
define("SUBSCRIBE", "Subscriviu-me!");
define("PROMO_PLAY", "Juga amb els teus amics.<br />Desafia'ls per demostrar qui és el millor.");
define("PROMO_RACE", "Competeix amb milers de jugadors<br /> de tot el món.");
define("PROMO_GROW", "Fes que el teu club creixi, <br/> converteix-te en el millor jugador <br/> i guanya premis.");
define("PROMO_PLAY_2", "Juga amb els teus amics.<br />Desafia'ls per demostrar<br /> qui és el millor.");
define("PROMO_GROW_2", "Fes que el teu club creixi, <br/> converteix-te en el millor jugador <br/> i guanya premis.");
define("TITLE_FORUM", "Fòrum del joc");
define("FORUM_DESCRIPTION", "Què esperes d'Trophy Leagues? Ja estàs jugant i esperaves alguna cosa més? Què t'agradaria que canviem? <br/> La teva opinió ens importa. Deixa els teus comentaris al nostre fòrum");
define("FORUM_JOIN", "Entra al fòrum");
define("FORM_CONFIRM", "Perfecte! Ja estas subscrit.");
define("FORM_TERMS", 'Accepto els <a href="http://trophyleagues.com/es/terminos-y-condiciones" target="_blank" class="terms-label">terminis i condicions</a> d\'ús');
define("MAILING_TEXT", "Introdueix el teu correu");
define("COOKIES_TEXT", 'Utilitzem cookies tècniques i analítiques per garantir que us donem la millor experiència al nostre lloc web.');
define("COOKIES_OK", 'Accepta i tanca');
define("COOKIES_INFO", 'Més informació');
define("", "");
