<?php

define("TITLE_INDEX", "TrophyLeagues - Manager online di calcio");
define("DESCRIPTION_INDEX", "Guida una squadra, istruisci i giocatori, gestisci l'economia, gioca e molto altro in TrophyLeagues.");
define("KEYWORDS_INDEX", "TrophyLeagues, trophy, manager calcio, TL manager, partita di calcio");
define("MENU_ABOUT", "Cos'è il TL?");
define("MENU_NEWS", "Notiziario");
define("MENU_COOP", "Collaborare");
define("MENU_FORUM", "Forum");
define("TITLE_REGISTER", "Iscriviti alla versione beta");
define("NAME", "Nome");
define("EMAIL", "E-mail");
define("COUNTRY", "Paese");
define("SEND", "Inviare");
define("TITLE_ABOUT", "Cos'è il <br />Trophy Leagues?");
define("ABOUT_DESCRIPTION", "Il gioco combina le funzioni di direzione tecnica della squadra, formazione, gestione economica del club, stadi, estetica, leghe e una comunità di appassionati di calcio. <br/> Trophy Leagues è un enorme gioco browser gratuito in cui i giocatori gestiscono la propria squadra di calcio.");
define("ABOUT_ACTION", "Non puoi aspettare un secondo per giocare? Iscriviti alla <a href='#form' class='tl-red'>versione beta</a>.");
define("TITLE_NEWS", "Notizie di gioco");
define("NEWS_DESCRIPTION", "Vi informeremo di tutte le novità del gioco, gli anticipi, le versioni di prova e di lancio.");
define("SUBSCRIBE", "Iscriviti!");
define("PROMO_PLAY", "Gioca con i tuoi amici. <br /> Sfidali per dimostrare chi è il migliore.");
define("PROMO_RACE", "Competi con migliaia di giocatori <br /> da tutto il mondo.");
define("PROMO_GROW", "Fai crescere il tuo club, <br /> diventare il miglior giocatore <br /> e vincere premi.");
define("PROMO_PLAY_2", "Gioca con i tuoi amici. <br /> Sfidali a mostrare <br /> chi è il migliore.");
define("PROMO_GROW_2", "Fai crescere il tuo club, <br /> diventare il miglior giocatore <br /> e vincere premi.");
define("TITLE_FORUM", "Forum di gioco");
define("FORUM_DESCRIPTION", "Cosa ti aspetti da Trophy Leagues? Stai già giocando e ti aspetti qualcosa di più? Cosa vorresti che cambiassimo? <br /> La tua opinione è importante per noi. Lascia i tuoi commenti nel nostro forum");
define("FORUM_JOIN", "Entra nel forum");
define("FORM_CONFIRM", "Perfetto! Sei già iscritto.");
define("FORM_TERMS", 'Accetto i <a href="http://trophyleagues.com/es/terminos-y-condiciones" target="_blank" class="terms-label">termini e le condizioni legali</a>');
define("MAILING_TEXT", "Inserisci la tua email");
define("COOKIES_TEXT", 'Utilizziamo cookie tecnici e analitici per assicurarti di darti la migliore esperienza sul nostro sito web.');
define("COOKIES_OK", 'Accetta e chiudi');
define("COOKIES_INFO", 'Ulteriori informazioni');
define("", "");
